export const LOAD_BOOKS_SUCCESS = 'LOAD_BOOKS_SUCCESS';
export const LOAD_BOOKS_BY_QUANTITY_SUCCESS = 'LOAD_BOOKS_BY_QUANTITY_SUCCESS';
export const LOAD_BOOKS_SORTED_BY_NEWEST = 'LOAD_BOOKS_BY_QUANTITY_SUCCESS';
export const CREATE_BOOK_SUCCESS = 'CREATE_BOOK_SUCCESS';
export const UPDATE_BOOK_SUCCESS = 'UPDATE_BOOK_SUCCESS';
export const DELETE_BO0K_SUCCESS = 'DELETE_BO0K_SUCCESS';

export const LOAD_POLISHWORDS_SUCCESS = 'LOAD_POLISHWORDS_SUCCESS';
export const LOAD_ENGLISHWORDS_SUCCESS = 'LOAD_ENGLISHWORDS_SUCCESS';

export const LOAD_USERS_SUCCESS = 'LOAD_USERS_SUCCESS';
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGOUT_USER_SUCCESS = 'LOGOUT_USER_SUCCESS';
export const CHECK_USER_IS_LOG_IN = 'CHECK_USER_IS_LOG_IN';

export const BEGIN_AJAX_CALL = 'BEGIN_AJAX_CALL';
export const AJAX_CALL_ERROR = 'AJAX_CALL_ERROR';

export const LOAD_CATEGORIES_SUCCESS = 'LOAD_CATEGORIES_SUCCESS';
export const CREATE_CATEGORY_SUCCESS = 'CREATE_CATEGORY_SUCCESS';
export const UPDATE_CATEGORY_SUCCESS = 'UPDATE_CATEGORY_SUCCESS';
export const DELETE_CATEGORY_SUCCESS = 'DELETE_CATEGORY_SUCCESS';

export const LOAD_CARRIERS_SUCCESS = 'LOAD_CARRIERS_SUCCESS';
export const CREATE_CARRIER_SUCCESS = 'CREATE_CARRIER_SUCCESS';
export const UPDATE_CARRIER_SUCCESS = 'UPDATE_CARRIER_SUCCESS';
export const DELETE_CARRIER_SUCCESS = 'DELETE_CARRIER_SUCCESS';

export const LOAD_COVERS_SUCCESS = 'LOAD_COVERS_SUCCESS';
export const CREATE_COVER_SUCCESS = 'CREATE_COVER_SUCCESS';
export const UPDATE_COVER_SUCCESS = 'UPDATE_COVER_SUCCESS';
export const DELETE_COVER_SUCCESS = 'DELETE_COVER_SUCCESS';

export const LOAD_AUTHORS_SUCCESS = 'LOAD_AUTHORS_SUCCESS';
export const CREATE_AUTHOR_SUCCESS = 'CREATE_AUTHOR_SUCCESS';
export const UPDATE_AUTHOR_SUCCESS = 'UPDATE_AUTHOR_SUCCESS';
export const DELETE_AUTHOR_SUCCESS = 'DELETE_AUTHOR_SUCCESS';

export const THROW_ERROR = 'THROW_ERROR';
export const EXIT_ERROR = 'EXIT_ERROR';