export const LOAD_BOOKS_SUCCESS = 'LOAD_BOOKS_SUCCESS';

export const LOAD_POLISHWORDS_SUCCESS = 'LOAD_POLISHWORDS_SUCCESS';
export const LOAD_ENGLISHWORDS_SUCCESS = 'LOAD_ENGLISHWORDS_SUCCESS';

export const LOAD_USERS_SUCCESS = 'LOAD_USERS_SUCCESS';
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGOUT_USER_SUCCESS = 'LOGOUT_USER_SUCCESS';
export const CHECK_USER_IS_LOG_IN = 'CHECK_USER_IS_LOG_IN';

export const BEGIN_AJAX_CALL = 'BEGIN_AJAX_CALL';
export const AJAX_CALL_ERROR = 'AJAX_CALL_ERROR';

export const LOAD_CATEGORIES_SUCCESS = 'LOAD_CATEGORIES_SUCCESS';
export const CREATE_CATEGORY_SUCCESS = 'CREATE_CATEGORY_SUCCESS';
export const UPDATE_CATEGORY_SUCCESS = 'UPDATE_CATEGORY_SUCCESS';
export const DELETE_CATEGORY_SUCCESS = 'DELETE_CATEGORY_SUCCESS';

export const LOAD_CARRIERS_SUCCESS = 'LOAD_CARRIERS_SUCCESS';
export const CREATE_CARRIER_SUCCESS = 'CREATE_CARRIER_SUCCESS';
export const UPDATE_CARRIER_SUCCESS = 'UPDATE_CARRIER_SUCCESS';
export const DELETE_CARRIER_SUCCESS = 'DELETE_CARRIER_SUCCESS';
